### PR TITLE
about page added

### PR DESCRIPTION
**Pull request by Jaiminkapopara**
about page added , details is outdated

### CODE REVIEW

**Review by Code-Knightt — CHANGES_REQUESTED** [review]
Shift the content of the page inside the data folder

**Comment by Code-Knightt** [comment]
## Experience the Future at Converse 2K23 - Where Innovation Meets Inspiration!

Prepare yourselves for an exhilarating journey into the realms of technology and creativity as the Information Technology & Artificial Intelligence and Data Science departments of Sarvajanik College of Engineering and Technology proudly present Converse 2K23, set to unfold on the 29th and 30th of September, 2023, under the dynamic banner of Kshitij.

### A Fusion of Tech and Artistry

Converse 2K23 is not your run-of-the-mill technical festival; it's a captivating fusion of cutting-edge technology and boundless creativity. With a dazzling array of 7 technical and 7 non-technical events, this festival promises to be a playground for the brightest minds and the most innovative souls. Dive headfirst into the world of IT, or let your creativity soar in non-technical domains like art, sports, and entrepreneurship.

### Ignite Your Passion

Whether you're a coding wizard, a debugging maestro, an aspiring entrepreneur, or simply someone who loves to explore new horizons, Converse 2K23 has something for everyone. Engage in intense coding competitions, professional grade mock interviews, or pitch your groundbreaking startup idea to an expert panel. On the flip side, showcase your artistic flair through acting, video-gaming, and a host of cultural events that will captivate your senses.

### Why Converse 2K23?

Converse 2K23 isn't just a festival; it's an opportunity to connect with like-minded individuals, learn from industry experts, and chart your course into the future of technology and innovation. So, mark your calendars and join us for an unforgettable experience that will leave you inspired, informed, and exhilarated. The future is here, and it's happening at Converse 2K23!

**Comment by Code-Knightt** [comment]
@Jaiminkapopara can you add this data on about page. We will merge it then. Also do ***not*** move the data to data folder. Directly write it into the about page in order to preserve formatting.

**Comment by Jaiminkapopara** [comment]
ya, sure.

**Review by Code-Knightt — APPROVED** [review]

**Comment by Code-Knightt** [comment]
Nice job

**Pull request merged**
